In [ ]:
# 과제

In [11]:
class Student:
    def __init__(self):
        self.num = 0
        self.name = ''
        self.age = 0
        self.school = ''
        self.cl_num = ''

    def inputData(self):
        self.name = input("이름을 입력하세요. ")
        self.age = eval(input("나이를 입력하세요. "))
        self.school = input("학교이름을 입력하세요. ")
        self.cl_num = input("강좌번호를 입력하세요. ")
        
    def __str__(self):
        return '%5s %10s %7s %10s %10s' % (self.num, self.name, self.age, self.school, self.cl_num)
    def __cmp__(self,other):
        return self.name == other.name
    def __call__(self,other): # 클래스를 함수처럼 사용하고자 할 때 오버라이딩
        st = []
        for student in other:
            std = Student()
            std.num = student[0]
            std.name = student[1]
            std.age = student[2]
            std.school = student[3]
            std.cl_num = student[4]
            st.append(std)
        return st

In [15]:
import pymysql

class maria:
    schoolname = "소정'S 토익학원"
    def __init__(self):
        self.conn = pymysql.connect(host='192.168.1.241', port=3306, user='root',
                           password='acorn1234Q!',db='academy', charset='utf8',
                                    autocommit=True)
        cor = self.conn.cursor()
        cor.execute("SHOW TABLES")
        tables = cor.fetchall()
        c = []
        for i in tables:
            if  i == ('student',):
                c.append(i)
        if len(c) != 0:
            student_table = "SELECT * FROM student"
            cor.execute(student_table)
            print('테이블이 있습니다. ')
        else:
            cor.execute("CREATE TABLE student(name VARCHAR(20), age INTEGER(20), school VARCHAR(20), cl_num VARCHAR(20)")
            print('sungjuk테이블을 생성하였습니다. ')
    def __del__(self):
        self.conn.close()

    def selectdb(self ):
        cur = self.conn.cursor()
        cur.callproc("student_select")
        if (cur.rowcount):
            stu = list(cur.fetchall())
        else :
            stu = 0;
        cur.close()
        return stu
   
    def insertdb(self,name, kor, mat, eng):
        cur = self.conn.cursor()
        args = (name, kor, mat, eng)
        cur.callproc("student_insert",args)
        cur.close()
       
    def updatedb(self, in_name, up_name):
        cur = self.conn.cursor()
        args = (in_name, up_name, 0)
        cur.callproc("student_update", args)
        cur.execute('SELECT @_student_update_2')
        result = cur.fetchone()
        if result==2 :
            print("수정할 이름이 없습니다.")
        else :
            print("성공적으로 수정하였습니다. ")
        cur.close()
        return result 
   
    def deletedb(self,in_name):
        cur = self.conn.cursor()
        args = (in_name, 0)
        cur.callproc("student_delete", args)
        cur.execute('SELECT @_student_delete_1')
        result = cur.fetchone()
        if result==2 :
            print("삭제할 이름이 없습니다.")
        else :
            print("성공적으로 삭제하였습니다. ")
        cur.close()
        return result

In [16]:
from math import  *
from statistics import *

class Management:
    
    def __init__(self):
        self.maria = maria()

    def M_select(self):
        data = self.maria.selectdb()
        st = []
        if (data):
            for student in data:
                std = Student()
                std.num=student[0]
                std.name = student[1]
                std.age = student[2]
                std.school = student[3]
                std.cl_num = student[4]
                st.append(std)
                
            # studdata=Student((data))
            print(maria.schoolname + "  성적 계산표 ")
            print('%5s %10s %7s %10s %10s' % ('번 호', '이 름', '나 이', '학 교', '강좌번호' ))      
            for stud in st:
                print( stud)                     
        else :
            print("데이터가 없습니다. ")
           
    def M_insert(self):
        stu = Student()
        stu.inputData()        
        self.maria.insertdb(stu.name, stu.age, stu.school, stu.cl_num)

    def M_update(self):
        name = input("검색할 이름을 입력하시오. ")
        cl_number = input("취소할 수강번호를 입력하시오. ")
        replace_cl_num = input("수정할 수강번호를 입력하시오. ")
        result = self.maria.updatedb(name, cl_number, replace_cl_num)      

    def M_delete(self):       
        name = input("검색할 이름을 입력하시요")
        self.maria.deletedb(name)

In [17]:
import sys
class Menu():
    def __init__(self):
        self.manage = Management()
       
    def work(self):
        menu = [ "전체검색(1), 입력(2), 수정(3), 삭제(4), 종료(9)"]
        manage = Management()
        while 1:
            sel = input(menu)
            if  sel == "1":
                manage.M_select()
                continue
            elif sel == "2":
                manage.M_insert()
                continue 
                
            elif sel =="3":
                manage.M_update()
                continue
                
            elif sel =="4":
                manage.M_delete()
                continue
                
            elif sel =="9":
                del(manage)
                sys.exit()
            else :
                print("잘못된 입력입니다. 다시입력 하시요")
                continue
                
menu = Menu()
menu.work()

테이블이 있습니다.
테이블이 있습니다.
['전체검색(1), 입력(2), 수정(3), 삭제(4), 종료(9)']1
소정'S 토익학원  성적 계산표
  번 호        이 름     나 이        학 교       강좌번호
    3        이소정      24         없음     CP0001
['전체검색(1), 입력(2), 수정(3), 삭제(4), 종료(9)']2
이름을 입력하세요. 김대현
나이를 입력하세요. 26
학교이름을 입력하세요. 제주대학교
강좌번호를 입력하세요. ONE001
['전체검색(1), 입력(2), 수정(3), 삭제(4), 종료(9)']1
소정'S 토익학원  성적 계산표
  번 호        이 름     나 이        학 교       강좌번호
    3        이소정      24         없음     CP0001
    4        김대현      26      제주대학교     ONE001
['전체검색(1), 입력(2), 수정(3), 삭제(4), 종료(9)']9

SystemExit: